qa/mount: run_shell specify stdout/stderr from user
To fix:
TypeError: a bytes-like object is required, not 'str'

Some user need to get a sting type object instead of the default
byte one.

Signed-off-by: Xiubo Li <xiubli@redhat.com>