cephadm: sort the list of inferred fsids
$ cephadm shell
ERROR: Cannot infer an fsid, one must be specified: ['1d5df33f-eb94-4a4f-b192-1d5e770ed0e7', 'unknown']
$ cephadm shell
ERROR: Cannot infer an fsid, one must be specified: ['unknown', '1d5df33f-eb94-4a4f-b192-1d5e770ed0e7']

Signed-off-by: Michael Fritch <mfritch@suse.com>
(cherry picked from commit 320956eb5ea5a43f0a0cd93fe580bc8d699eff1b)