mgr/volumes: add missing OpSmException import
fixes mypy error:

volumes/fs/operations/versions/__init__.py: note: In member "upgrade_legacy_subvolume" of class "SubvolumeLoader":
volumes/fs/operations/versions/__init__.py:56: error: Name 'OpSmException' is not defined

Signed-off-by: Michael Fritch <mfritch@suse.com>