mgr: balancer: fixed mistype "AttributeError: 'Logger' object has no attribute 'err'"
Signed-off-by: Konstantin Shalygin <k0ste@k0ste.ru>
(cherry picked from commit 2062e84c7a33fc5170740f2d60d07ddf62085457)