cls/rbd: silence the log of get metadata error
When getting the qos of an image without qos set,
there is a lot of printing in the OSD log file.
```
2018-12-07 15:23:51.122 7f01de695700  0 <cls> /home/swb/ceph/ceph-dev/src/cls/rbd/cls_rbd.cc:3728: error get metadata: (2) No such file or directory
```

Signed-off-by: songweibin <song.weibin@zte.com.cn>
(cherry picked from commit d2c1541d024d3c862e84bf1ff4b3d25634a08042)

Conflicts:
	src/cls/rbd/cls_rbd.cc