mgr/volumes: use keyword instead of positional arg
the placement spec was being passed as `service_id`

fixes mypy error:

volumes/fs/fs_util.py: note: In function "create_mds":
volumes/fs/fs_util.py:37: error: Argument 2 to "ServiceSpec" has incompatible type "PlacementSpec"; expected "Optional[str]"

Signed-off-by: Michael Fritch <mfritch@suse.com>