test: revert to default mount state in test_cephfs:test_mount_root()
without this tests written after test_mount_root() in the source
were failing with

     cephfs.LibCephFSStateError: You cannot perform that operation on a
     CephFS object in state initialized.

... since the test fiddles with the default mount which is root.

Signed-off-by: Venky Shankar <vshankar@redhat.com>
(cherry picked from commit db8b8a6791060eeb4aa10d00ffbb56e71a22142e)