Fixes following compiling error:
src/test/encoding/ceph_dencoder.cc: In instantiation of ‘void DencoderBase<T>::generate() [with T = rgw_data_sync_status]’:
src/test/encoding/ceph_dencoder.cc:483:1:   required from here
src/test/encoding/ceph_dencoder.cc:134:38: error: ‘generate_test_instances’ is not a member of ‘rgw_data_sync_status’
src/test/encoding/ceph_dencoder.cc: In instantiation of ‘void DencoderBase<T>::generate() [with T = rgw_data_sync_marker]’:
src/test/encoding/ceph_dencoder.cc:483:1:   required from here
src/test/encoding/ceph_dencoder.cc:134:38: error: ‘generate_test_instances’ is not a member of ‘rgw_data_sync_marker’
src/test/encoding/ceph_dencoder.cc: In instantiation of ‘void DencoderBase<T>::generate() [with T = rgw_data_sync_info]’:
src/test/encoding/ceph_dencoder.cc:483:1:   required from here
src/test/encoding/ceph_dencoder.cc:134:38: error: ‘generate_test_instances’ is not a member of ‘rgw_data_sync_info’
src/test/encoding/ceph_dencoder.cc: In instantiation of ‘void DencoderBase<T>::generate() [with T = rgw_meta_sync_status]’:
src/test/encoding/ceph_dencoder.cc:483:1:   required from here
src/test/encoding/ceph_dencoder.cc:134:38: error: ‘generate_test_instances’ is not a member of ‘rgw_meta_sync_status’
src/test/encoding/ceph_dencoder.cc: In instantiation of ‘void DencoderBase<T>::generate() [with T = rgw_meta_sync_marker]’:
src/test/encoding/ceph_dencoder.cc:483:1:   required from here
src/test/encoding/ceph_dencoder.cc:134:38: error: ‘generate_test_instances’ is not a member of ‘rgw_meta_sync_marker’
src/test/encoding/ceph_dencoder.cc: In instantiation of ‘void DencoderBase<T>::generate() [with T = rgw_meta_sync_info]’:
src/test/encoding/ceph_dencoder.cc:483:1:   required from here
src/test/encoding/ceph_dencoder.cc:134:38: error: ‘generate_test_instances’ is not a member of ‘rgw_meta_sync_info’
make[3]: *** [src/CMakeFiles/ceph-dencoder.dir/test/encoding/ceph_dencoder.cc.o] Error 1

Signed-off-by: runsisi <runsisi@zte.com.cn>